test promote helm chart 3.x

diff --git a/.github/workflows/helm-version-promote.yml b/.github/workflows/helm-version-promote.yml
--- a/.github/workflows/helm-version-promote.yml
+++ b/.github/workflows/helm-version-promote.yml
@@ -15,6 +15,34 @@ on:
         description: "New CSI proxy version (optional)"
         required: false
         type: string
+      semantic_bump_type:
+        description: "What version type (major, minor, or patch) to bump"
+        required: true
+        type: string
+
+  workflow_dispatch:
+    inputs:
+      agent_version:
+        description: "New agent version (optional)"
+        required: false
+        type: string
+      controller_version:
+        description: "New controller version (optional)"
+        required: false
+        type: string
+      csi_version:
+        description: "New CSI proxy version (optional)"
+        required: false
+        type: string
+      semantic_bump_type:
+        description: what version type (major, minor, or patch) to bump
+        required: true
+        type: choice
+        default: Patch
+        options:
+          - Major
+          - Minor
+          - Patch
 
 permissions:
   contents: write
@@ -27,8 +55,15 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: datafy-io/datafy-agent-helm
-          ref: master
+          ref: test-external-update
           token: ${{ secrets.GH_PUSH_TOKEN }}
+
+      - name: Validate inputs
+        run: |
+          if [[ -z "${{ inputs.agent_version }}" && -z "${{ inputs.controller_version }}" && -z "${{ inputs.csi_version }}" ]]; then
+            echo "Error: At least one of agent_version, controller_version, or csi_version must be provided."
+            exit 1
+          fi
 
       - name: Read current appVersion
         id: read_version
@@ -60,9 +95,35 @@ jobs:
         run: |
           yq -i ".appVersion = \"${{ steps.new_version.outputs.new }}\"" Chart.yaml
 
+      - name: Read current chart version
+        id: update_chart_version
+        run: |
+          current_chart_version=$(yq '.version' Chart.yaml)
+          echo "current chart version=$current_chart_version"
+          echo "current_chart_version=$current_chart_version" >> $GITHUB_ENV
+
+          bump_type_raw="${{ inputs.semantic_bump_type }}"
+          bump_type=$(echo "$bump_type_raw" | tr '[:upper:]' '[:lower:]')
+          echo "bump_type=$bump_type" >> $GITHUB_ENV
+
+      - name: Bump Version
+        id: bump
+        uses: cbrgm/semver-bump-action@main
+        with:
+          current-version: ${{ env.current_chart_version }}
+          bump-level: ${{ env.bump_type }}
+
+      - name: Update chart version
+        run: |
+          NEW_CHART_VERSION=${{ steps.bump.outputs.new_version }}
+          echo $NEW_CHART_VERSION
+
+          echo "new chart version=$NEW_CHART_VERSION (bump: ${{ env.bump_type }})"
+          yq -i ".version = \"${NEW_CHART_VERSION}\"" Chart.yaml
+
       - name: Install helm-docs
         run: |
-          curl -sSL https://github.com/norwoodj/helm-docs/releases/latest/download/helm-docs_Linux_x86_64.tar.gz | tar -xz
+         curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz | tar -xz
           sudo mv helm-docs /usr/local/bin/
 
       - name: Regenerate Helm docs
@@ -75,3 +136,12 @@ jobs:
           git add Chart.yaml README.md || true
           git commit -m "chore: update appVersion to ${{ steps.new_version.outputs.new }}" || echo "No changes to commit"
           git push
+
+  release_helm_chart:
+    needs: [ update ]
+    permissions:
+      id-token: write
+      contents: write
+    uses: datafy-io/datafy-agent-helm/.github/workflows/release.yaml@test-external-update
+    secrets:
+      PRODUCTION_AWS_ROLE_ARN: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
